### ISSUE TITLE
Yajta fails when trying to instrument .class files

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/yajta#10]
For example, `module-info.class` or files like `BC11XDHPrivateKey.class` in the META-INF folder or maven artifacts are not instrumented properly by Yajta. It is more convenient to continue the instrumentation of these classes after an error, instead of throwing an exception and stopping the instrumentation entirely.

**Comment by nharrand** [comment]
Should be fixed with release 2.0.2

**Comment by nharrand** [comment]
@cesarsotovalero I can close this one right?

**Comment by cesarsotovalero** [comment]
@nharrand  Sure, it's fixed now.
