### ISSUE TITLE
Yajta tries to instrument non-class files

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/yajta#8]
The offline instrumentation fails if there are other files that are not classes in the target/classes directory. Yajta should at least check that the file ends with `.class` before attempting its instrumentation.

**Comment by nharrand** [comment]
This should not happen. Let me know if it happens again with version 2.0.2

**Comment by cesarsotovalero** [comment]
@nharrand It seems to be fixed with version 2.0.2
